version: "3.8"
services:
  database:
    image: postgres
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: "darkman"
      POSTGRES_PASSWORD: "sossuseta"
      POSTGRES_DB: "darkforest"