version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: apina  
      POSTGRES_PASSWORD: mies 
      POSTGRES_DB: darkforest
    ports:
     - 5432:5432
    volumes:
     - ./data:/var/lib/postgresql/data