
type User {
	id: String!
	email: String!
	username: String!
	villages: [Village!]!
}

enum BuildingType {
	Warehouse
	Silo
	Hospital
	School
	University
}

type Building {
	id: ID
	buildingType: BuildingType
	level: Int
	maxStorageCapacity: Int
	goldStored: Int
	goldProductionRate: Int
	woodStored: Int
	woodProductionPerHour: Int
}

enum UnitType {
	Rocket
	Tank
}

type Unit {
	id: ID
	unitType: UnitType
	amount: Int
}

type Village {
	id: ID
	doctors: Int
	soldires: Int
	engineers: Int
	fertility: Int
	teachers: Int
	scientists: Int
	buildings: [Building!]!
	units: [Unit!]!
}

type Viewer {
	user: User
}

type LoginResponse {
	token: String!
	viewer: Viewer!
}

type RegisterResponse {
	viewer: Viewer!
}

enum SquareType {
	Water
	Mountain
	Desert
}

type Square {
	id: ID
	x: Int
	y: Int
	squareType: SquareType
}

type MapResult {
	squares: [Square!]!
}

type Query {
	email: String!
	username: String!
	viewer: Viewer! 
	user: User!
	map(x: Int, y: Int, width: Int, height: Int): MapResult
}

type Mutation {
	register(email: String!, username: String!, password: String!): RegisterResponse
	login(username: String!, password: String!): LoginResponse!
}