
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

name: Build-frontend
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: cd web && bun install && bun run build